### ISSUE TITLE
Unable to run on Windows

### ISSUE THREAD

**Issue by kdheepak** [svenstaro/upx-action#41]
Thanks for making this action!

I'm having an issue running it on Windows:

```
Run svenstaro/upx-action@v2
  with:
    files: target/x86_64-pc-windows-gnu/release/taskwarrior-tui.exe
  
    args: -9
    strip: false
  env:
    RUSTFLAGS: -C target-feature=+crt-static
    MACOSX_DEPLOYMENT_TARGET: 10.7
Downloading UPX...
C:\ProgramData\Chocolatey\bin\choco.exe install upx --no-progress --version=4.2.2
Chocolatey v2.2.2
Installing the following packages:
upx
By installing, you accept licenses for the packages.
[NuGet] Error downloading 'upx.4.2.2' from 'https://community.chocolatey.org/api/v2/package/upx/4.2.2'.
[NuGet] Response status code does not indicate success: 503 (Service Unavailable: Back-end server is at capacity).
[NuGet] Error downloading 'upx.4.2.2' from 'https://community.chocolatey.org/api/v2/package/upx/4.2.2'.
[NuGet] Response status code does not indicate success: 503 (Service Unavailable: Back-end server is at capacity).
upx not installed. An error occurred during installation:
 Error downloading 'upx.4.2.2' from 'https://community.chocolatey.org/api/v2/package/upx/4.2.2'.
upx package files install failed with exit code 1. Performing other installation steps.
The install of upx was NOT successful.
upx not installed. An error occurred during installation:
 Error downloading 'upx.4.2.2' from 'https://community.chocolatey.org/api/v2/package/upx/4.2.2'.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - upx (exited 1) - upx not installed. An error occurred during installation:
 Error downloading 'upx.4.2.2' from 'https://community.chocolatey.org/api/v2/package/upx/4.2.2'.
Error: The process 'C:\ProgramData\Chocolatey\bin\choco.exe' failed with exit code 1
D:\a\_actions\svenstaro\upx-action\v2\dist\index.js:1825
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process 'C:\ProgramData\Chocolatey\bin\choco.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\svenstaro\upx-action\v2\dist\index.js:1825:25)
    at ExecState.CheckComplete (D:\a\_actions\svenstaro\upx-action\v2\dist\index.js:1808:18)
    at ChildProcess.<anonymous> (D:\a\_actions\svenstaro\upx-action\v2\dist\index.js:1702:27)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v20.8.1
```

Do you happen to know what is going on?

**Comment by svenstaro** [comment]
You can see in the log it says you hit a 503. Try again later, I guess.

**Comment by kdheepak** [comment]
I tried a couple of times and got the same error but now it works! Sorry for the noise!
