### ISSUE TITLE
"Syntax error: Unterminated quoted string" when compressing GraalVM native image on linux arm64

### ISSUE THREAD

**Issue by jumarko** [svenstaro/upx-action#42]
We are using upx-action to compress graalvm native image binary on variety of architectures including linux/x86, macos/x86, macos/arm64, and windows/amd64.

I'm trying to add support for linux/arm64 (aarch64) by using arm64 runners (see https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/).

After the Graalvm native image is generated we try to compress it with the following:
```

      - name: Compress binary
        uses: svenstaro/upx-action@v2
        with:
          files: cli/target/myexecutable
```

 which fails:
```
Run svenstaro/upx-action@v2
Running strip...
/usr/bin/strip cli/target/myexecutable
Downloading UPX...
/usr/bin/curl -LO https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  576k  100  576k    0     0  1801k      0 --:--:-- --:--:-- --:--:-- 1801k
/usr/bin/tar xvJf upx-4.2.2-amd64_linux.tar.xz --strip-components=1 upx-4.2.2-amd64_linux/upx
upx-4.2.2-amd64_linux/upx
Running UPX...
/tmp/upx-action-CTD35H/upx cli/target/myexecutable
/tmp/upx-action-CTD35H/upx: 1: �: not found
/tmp/upx-action-CTD35H/upx: 1: cannot open UPX!�: No such file
/tmp/upx-action-CTD35H/upx: 1: Syntax error: Unterminated quoted string
Error: The process '/tmp/upx-action-CTD35H/upx' failed with exit code 2
/home/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:1825
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^
Error: The process '/tmp/upx-action-CTD35H/upx' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:1825:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:1808:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/svenstaro/upx-action/v2/dist/index.js:1702:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12)
Node.js v20.18.0
```

It seems it's downloading the upx binary for wrong architecture (amd64):
```
/usr/bin/curl -LO https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
```

**Comment by IlyaGulya** [comment]
Yeah, same issue here: https://github.com/IlyaGulya/vd-tool/actions/runs/13164522610/job/36741393388#step:5:29

**Comment by svenstaro** [comment]
I only really passively maintain this but I would appreciate a PR to fix this.
